config/routes.rb
Rails.application.routes.draw do
  root 'home#index', as: 'home'
  resources :blood_donors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood_donor.rb
class BloodDonor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blood_donors_controller.rb
class BloodDonorsController < ApplicationController
  before_action :set_blood_donor, only: [:show, :edit, :update, :destroy]

  # GET /blood_donors
  # GET /blood_donors.json
  def index
    @blood_donors = BloodDonor.all
  end

  # GET /blood_donors/1
  # GET /blood_donors/1.json
  def show
  end

  # GET /blood_donors/new
  def new
    @blood_donor = BloodDonor.new
  end

  # GET /blood_donors/1/edit
  def edit
  end

  # POST /blood_donors
  # POST /blood_donors.json
  def create
    @blood_donor = BloodDonor.new(blood_donor_params)

    respond_to do |format|
      if @blood_donor.save
        format.html { redirect_to @blood_donor, notice: 'Blood donor was successfully created.' }
        format.json { render :show, status: :created, location: @blood_donor }
      else
        format.html { render :new }
        format.json { render json: @blood_donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blood_donors/1
  # PATCH/PUT /blood_donors/1.json
  def update
    respond_to do |format|
      if @blood_donor.update(blood_donor_params)
        format.html { redirect_to @blood_donor, notice: 'Blood donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @blood_donor }
      else
        format.html { render :edit }
        format.json { render json: @blood_donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_donors/1
  # DELETE /blood_donors/1.json
  def destroy
    @blood_donor.destroy
    respond_to do |format|
      format.html { redirect_to blood_donors_url, notice: 'Blood donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood_donor
      @blood_donor = BloodDonor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_donor_params
      params.require(:blood_donor).permit(:name, :phone_number, :blood_type, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blood_donors_helper.rb
module BloodDonorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blood_donors/_form.html.erb
<%= form_with(model: blood_donor, local: true) do |form| %>
  <% if blood_donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blood_donor.errors.count, "error") %> prohibited this blood_donor from being saved:</h2>

      <ul>
      <% blood_donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :blood_type %>
    <%= form.text_field :blood_type %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blood_donors/edit.html.erb
<h1>Editing Blood Donor</h1>

<%= render 'form', blood_donor: @blood_donor %>

<%= link_to 'Show', @blood_donor %> |
<%= link_to 'Back', blood_donors_path %>

app/views/blood_donors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blood Donors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Blood type</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_donors.each do |blood_donor| %>
      <tr>
        <td><%= blood_donor.name %></td>
        <td><%= blood_donor.phone_number %></td>
        <td><%= blood_donor.blood_type %></td>
        <td><%= blood_donor.address %></td>
        <td><%= link_to 'Show', blood_donor %></td>
        <td><%= link_to 'Edit', edit_blood_donor_path(blood_donor) %></td>
        <td><%= link_to 'Destroy', blood_donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blood Donor', new_blood_donor_path %>

app/views/blood_donors/new.html.erb
<h1>New Blood Donor</h1>

<%= render 'form', blood_donor: @blood_donor %>

<%= link_to 'Back', blood_donors_path %>

app/views/blood_donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blood_donor.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @blood_donor.phone_number %>
</p>

<p>
  <strong>Blood type:</strong>
  <%= @blood_donor.blood_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @blood_donor.address %>
</p>

<%= link_to 'Edit', edit_blood_donor_path(@blood_donor) %> |
<%= link_to 'Back', blood_donors_path %>

app/views/home/index.html.erb
<center>
	
<h1>Kamu bisa lihat data pendonor nya disini</h1>
<p> <a target="_blank" href="https://docs.google.com/spreadsheets/d/15vhv-u-2WXW2t_unlM_WItyVeNDYK6cUeNeOYfkpVgE/edit?usp=drivesdk">Data Pendonor </a> </p>
<p>gunakan Ctrl + F untuk mencari data yang diinginkan</p>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Darahkendari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>